# Generated by Django 3.0.3 on 2020-02-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_volunteerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
