# Generated by Django 3.0.3 on 2020-02-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_college_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
            preserve_default=False,
        ),
    ]
