# Generated by Django 3.0.3 on 2020-02-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_volunteerprofile_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
