# Generated by Django 3.0.3 on 2020-02-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='department',
        ),
    ]
